U chroot Dependency

diff --git a/.github/actions/action.yml b/.github/actions/action.yml
--- a/.github/actions/action.yml
+++ b/.github/actions/action.yml
@@ -425,6 +425,43 @@ runs:
         CONFIG_TMPFS_POSIX_ACL=y
         EOF
 
+    - name: Ubuntu Chroot 
+      shell: bash
+      run: |
+        set -euo pipefail
+        cd "$CONFIG/kernel_platform"
+        cat >> common/arch/arm64/configs/gki_defconfig <<EOF
+        
+        # Core Namespace Support (Required for Isolation)
+        CONFIG_NAMESPACES=y
+        CONFIG_PID_NS=y
+        CONFIG_UTS_NS=y
+        CONFIG_MNT_NS=y
+        CONFIG_IPC_NS=y
+
+        # Essential Filesystems for Hardware Access
+        CONFIG_DEVTMPFS=y
+        CONFIG_PROC_FS=y
+        CONFIG_SYSFS=y
+
+        # Running x86_64 Binaries Natively
+        CONFIG_BINFMT_MISC=y
+        CONFIG_BINFMT_SCRIPT=y
+        CONFIG_BINFMT_ELF=y
+        
+        # GUI Applications Support
+        # IPC mechanisms (required by many apps and daemons)
+        # KDiskMark and Brave Browser will fail without these
+        CONFIG_SYSVIPC=y
+        # CONFIG_SYSVIPC_SYSCTL is not set
+        # CONFIG_PROC_SYSCTL is not set
+        CONFIG_POSIX_MQUEUE=y
+        
+        # Docker Support in Chroot
+        CONFIG_CGROUPS=y
+        CONFIG_CGROUP_DEVICE=y
+        CONFIG_MEMCG=y
+
     - name: Add Oneplus BBR
       shell: bash
       run: |
